### ISSUE TITLE
Allow for updating form fields that are not yet rendered

### ISSUE THREAD

**Issue by alexjsdev** [final-form/final-form-calculate#15]
### Are you submitting a **bug report** or a **feature request**?
I'm not sure if this is a bug or a new feature, I'm leaning towards new feature...

### What is the current behavior?
I have a situation where I have async zipcode validation/pre-fill in a wizard style form, the zipcode question of the form comes early in the question set and then upon the user entering a valid zip (which gets validated against an api endpoint) it returns the city and state that needs to get prefilled for the registration portion of the form (on another not yet rendered/mounted page)... it seems like this is not currently supported functionality, or I'm doing something totally wrong.

### What is the expected behavior?
The form values i want to prefill will be prefilled in final form state and rendered with value when the user gets to the page that renders those fields.

### Sandbox Link
I created this very quick and dirty example to demonstrate how it works when both fields are rendered but does not work when you hide the second zipCode field... https://codesandbox.io/s/lyk398lmll

### What's your environment?

final-form-calculate@1.1.0
react-final-form@3.3.0

**Comment by alexjsdev** [comment]
@erikras I don't mean to bug you, but i'd love to help if you'd accept a PR for this, but could you point me in the right direction? I really need this functionality...

If i'm not taking the right approach, what am I missing? is there a better way to accomplish what i need to do?

**Comment by greeksolid** [comment]
@alexjsdev I had similar requirements with you (change value of a related field that is rendered on another step of a wizard form). An ugly way I found to get around this problem is to declare a field with the same name as the one I wanted to change, in the container component of the wizard so final-form-calculate can see it as a registered field and change its value.

example : `<Field name="fieldYouWantToChange" component={() => null} />`

I have not yet noticed any problems with this except ugly hacky code.

**Comment by erikras** [comment]
It can also be done in bulk with something like this. https://github.com/final-form/final-form/issues/102#issuecomment-380408599

However, having thought about _why_ I chose to not allow changes to non-registered fields, I cannot defend the decision. It makes the library _less_ flexible. So I'm going to reverse that decision.

**Comment by erikras** [comment]
You can now update non-registered fields in [`final-form@4.8.1`](https://github.com/final-form/final-form/releases/tag/v4.8.1).
