### ISSUE TITLE
Allow promises as updates return values

### ISSUE THREAD

**Issue by TiuSh** [final-form/final-form-calculate#16]
### What is the current behavior?

`UpdatesByName` and `UpdatesForAll` functions don't handle Promises as return values.

### What is the expected behavior?

I'd love to be able to handle asynchronous updates using Promises inside `updates` functions.

### Other information

I already experimented a little bit with the code, and I'm quite happy with the result. I'm ready to create a PR if you're willing to accept this feature !

**Comment by TiuSh** [comment]
Did anyone take a look on this issue & PR ?

**Comment by erikras** [comment]
Looks good. Will merge and publish on Monday. Please remind me if I don't.

**Comment by TiuSh** [comment]
Nice ! 👍

**Comment by peterpetre** [comment]
@erikras Reminder!

**Comment by erikras** [comment]
Published in [`v1.2.0`](https://github.com/final-form/final-form-calculate/releases/tag/v1.2.0).
