### ISSUE TITLE
FieldPattern supports array of regular expressions

### ISSUE THREAD

**Issue by JustWalters** [final-form/final-form-calculate#32]
### Are you submitting a **bug report** or a **feature request**?

Documentation Bug

### What is the current behavior?

FieldPattern allows a string, a RegExp, or an array of either. The documentation and typings suggest that a provided array can only contain strings.

### What is the expected behavior?

Documentation and typings accurately reflect accepted types.

### Sandbox Link

https://codesandbox.io/s/react-typescript-h4dyg

The decorator works as expected, but "field" is reported as having the wrong type.

### What's your environment?

"final-form": "4.18.5",
"final-form-calculate": "1.3.1",
"react": "^16.2.0",
"react-final-form": "6.3.0",

**Comment by gorilazish** [comment]
Is it possible to submit a PR for this issue?

**Comment by erikras** [comment]
Published fix in [`v1.3.2`](https://github.com/final-form/final-form-calculate/releases/tag/v1.3.2).
