### ISSUE TITLE
Provide FormValues for createDecorator

### ISSUE THREAD

**Issue by A11oW** [final-form/final-form-calculate#38]
If FormValues type in typescript is specified for a Form, then type 'Decorator<object>' is not assignable to type 'Decorator<FormValues>'

**Comment by erikras** [comment]
Published fix in [`v1.3.2`](https://github.com/final-form/final-form-calculate/releases/tag/v1.3.2).

**Comment by twgraham** [comment]
Sorry to bring this back up, but as [mentioned in the PR](https://github.com/final-form/final-form-calculate/pull/39#issuecomment-686248857), this fix is not available in 1.3.2. Are we able to get a new release with this fix?

**Comment by sscotth** [comment]
@erikras This doesn't appear to be published

![image](https://user-images.githubusercontent.com/1010488/99717812-88cffa80-2a6f-11eb-8610-7e24b9806dd7.png)

**Comment by dheeraj-jn** [comment]
@erikras The fix is not available in 1.3.2. Could you republish this please?

**Comment by nandanshanubhag** [comment]
@erikras any update on republishing?
