### ISSUE TITLE
Allow fieldName to be an array

### ISSUE THREAD

**Issue by robinvdvleuten** [final-form/final-form-calculate#4]
### Are you submitting a **bug report** or a **feature request**?

A feature request

### What is the current behavior?

Currently you can pass a field name as string or a regex.

### What is the expected behavior?

It would be nice to have array support as well.

**Comment by erikras** [comment]
Published fix in [`v1.1.0`](https://github.com/final-form/final-form-calculate/releases/tag/v1.1.0).
